package WebService::Strava::Gear;

use v5.010;
use strict;
use warnings;
use Moo;

# ABSTRACT: An Athelete Gear Object

# VERSION: Generated by DZP::OurPkg:Version

=head1 SYNOPSIS

  This class shouldn't be directly instantiated.

=head1 DESCRIPTION

  This is a parent class to 'Gear' objects. Currently Strava
  has two different Gear types Shoe and Bike. They entirely
  the same, however a bike can have a frame and model.

=cut

has 'id'              => ( is => 'ro' );
has 'primary'         => ( is => 'rw' ); 
has 'name'            => ( is => 'rw' );
has 'distance'        => ( is => 'rw' );
has 'brand_name'      => ( is => 'rw' );
has 'model_name'      => ( is => 'rw' );
has 'description'     => ( is => 'rw' );
has 'resource_state'  => ( is => 'rw' );

1;
