package WebService::Strava::Athlete::Gear::Shoe;

use v5.010;
use strict;
use warnings;
use Moo;

extends 'WebService::Strava::Athlete::Gear';

# ABSTRACT: An Athlete's Shoe 

# VERSION: Generated by DZP::OurPkg:Version

=head1 SYNOPSIS

  Provides a shoe object

=head1 DESCRIPTION

  Though currently gear items can only be retrieved if Strava
  extend the API to be able to update/change/remove gear, this
  will provide the framework to easily extend the library.

  Shoes are essentially a plain gear object.

=cut

1;
